// dashboard-web/src/lib/registries/tiktokStatusSets.ts
//
// Shared TikTok ad-group status sets. Previously lived in
// CampaignsTableRow.tsx (TIKTOK_OFF_STATUSES + TIKTOK_ACTIVE_ENOUGH).
// Extracted here so statusClassification.ts can reuse them.

export const TIKTOK_OFF_STATUSES = new Set([
  'ADGROUP_STATUS_DISABLE',
  'ADGROUP_STATUS_TIMEDOUT',
  'ADGROUP_STATUS_FROZEN',
  'ADGROUP_STATUS_ARCHIVED',
  'ADGROUP_STATUS_DELETE',
  'ADGROUP_STATUS_CAMPAIGN_DISABLE',
  'ADGROUP_STATUS_ADVERTISER_AUDIT_DENY',
  'ADGROUP_STATUS_ADVERTISER_FROZEN',
  'ADGROUP_STATUS_ADVERTISER_BUDGET_EXCEED',
  'ADGROUP_STATUS_BALANCE_EXCEED',
  'ADGROUP_STATUS_AUDIT_DENY',
]);

export const TIKTOK_ACTIVE_ENOUGH = new Set([
  'ADGROUP_STATUS_DELIVERY_OK',
  'ADGROUP_STATUS_BUDGET_EXCEED',
  'ADGROUP_STATUS_AUDIT',
  'ADGROUP_STATUS_REVIEWING',
  'ADGROUP_STATUS_NOT_START',
]);
